snyk/snyk-api-import

src/lib/org/index.ts
src/log-failed-imports.ts
src/scripts/create-orgs.ts

Grab the org sources data too after creating the org as it is needed in the next step of import.
- [TECHSERV-685](https://snyksec.atlassian.net/browse/TECHSERV-685)

feat: get the org sources info after creating the org

---

src/common.ts
src/log-imported-batch.ts
src/scripts/import-projects.ts
test/generate-log-file-names.ts
test/scripts/import-projects.test.ts

Log the processed batches as they easily get lost in the polling logs.
https://github.com/snyk-tech-services/snyk-api-import/issues/50

feat: log batches to file for progress

---

README.md
src/log-imported-targets.ts
src/scripts/import-projects.ts

Show a user readable import date & time
- https://github.com/snyk-tech-services/snyk-api-import/issues/54

feat: show user friendly import date

---

README.md
src/lib/import/index.ts
src/lib/types.ts

Pass through `exlcusionGlobs` + update examples with `files` usage

feat: send exclusionGlobs if set

---

.nvmrc
package.json

Use npx fort snyk protect to skip merging frequent upgrade PRs and not introduce snyk as a dep.

feat: use npx to run snyk protect

---

.github/CODEOWNERS
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md
Contributor-Agreement.md
LICENSE

Add missing open source documentation

docs: update open source documentation

---

src/lib/poll-import/index.ts

Try to propagate true error from API on why a poll failed.

feat: log more of the polling error

---

test/scripts/github.test.ts

test: re-use existing gh token

---

package.json

Use latest request manager with better debug output on error

feat: upgrade snyk-request-manager to 1.3.0 with better DEBUG handling

---

src/lib/import/index.ts
src/lib/org/index.ts
src/lib/project/index.ts

Trim ORG_ID variable in case it has some blank space

fix: trim spaces from variable ORG_ID

---

src/lib/import/index.ts
src/scripts/import-projects.ts

Tweak the messaging to point user to logs where needed.

feat: link to logs in user messages

---

README.md

Small formatting fix in README to correct heading style

chore: fix README h1 formatting

---

docs/import.md

Update the documentation to include Gitlab example

Update with Gitlab example

---

README.md

Update link to example import files in docs

chore: fix documentation link

---

docs/import-data.md

Update import data instructions

chore: Update import data instructions

---

package.json

fix: use latest non-vulnerable snyk cli

---

.circleci/config.yml

Configure slack orb to get notifications in Slack

feat: configure slack orb

---

.circleci/config.yml

Try to fix the release by downgrading to last working semantic-release version

fix: downgrade semantic-release

---

.circleci/config.yml

Stik with Node 12 to try and resolve the `pkg` step issue `This experimental syntax requires enabling one of the following parser plugin(s): 'flow, typescript' (6:7)
/home/circleci/project/node_modules/@octokit/openapi-types/generated/types.ts`

feat: use node 12 on circle

---

.circleci/config.yml

Downgrading to 4.48 (version that works locally) to
try and fix the error:
Error! This experimental syntax requires enabling one of the following parser plugin(s): 'flow, typescript' (6:7)\n" + /home/circleci/project/node_modules/@octokit/openapi-types/generated/types.ts

fix: downgrade pkg to version 4.48 to fix release issue

---

.circleci/config.yml
.gitignore
.npmrc
.nvmrc
package.json

Align local & ci deps + install

feat: add release packages to package.json

---

.circleci/config.yml
.gitignore
.npmrc
package-lock.json
package.json
src/scripts/github/list-repos.ts
tsconfig.json

Terrible hacky workaround for the `pkg` failure that is occurring because a transitive types package is not building when running `pkg`.
Introduce a lockfile so I can control the dep versions by manually resolving to the relevant package 😢

fix: manually pin problem dependency that breaks pkg step

---

.releaserc
package.json

feat: switch to next from pkg

---

package.json

Use latest snyk-request-manager that has vulnerability and bug fixes available

feat: bump snyk-request-manager to 1.4.0

---

src/scripts/import-projects.ts

use pMap instead of forEach to iterate over all targets when checking if previously imported, when tested on an input of 14k targets this reduced the time to process by over 50%.

feat: use pMap to iterate over all items during imported check

---

test/scripts/import-projects.test.ts

Re-enable disabled test due to upstream issues.

test: re-enable test that was failing due to upstream issues

---

.circleci/config.yml
.releaserc
package.json

Regression test for binary build via nexe to ensure binary is healthy

test: add a binary regression test to ensure it is built

---

README.md

Create an FAQ for some issues & how to resolve them as they arise. Adding in for the `ulimit` issue that can occur if too many open file reading/writing handles are open. Improvements work is on-going to reduce the possibility of reaching the limits as well.

chore: add FAQ to readme about ulimit

---

docs/import-data.md
docs/import.md
docs/mirror-github.md
docs/orgs.md
src/cmds/import:data.ts
src/cmds/list:imported.ts
src/cmds/orgs:create.ts
src/cmds/orgs:data.ts
src/lib/api/orgs/index.ts
src/loggers/log-created-org.ts
src/loggers/log-failed-org.ts
src/scripts/create-orgs.ts
src/scripts/generate-imported-targets-from-snyk.ts
src/scripts/github/list-orgs.ts
test/lib/orgs.test.ts
test/system/__snapshots__/basic.test.ts.snap
test/system/__snapshots__/generate-imported-targets-from-snyk.test.ts.snap
test/system/__snapshots__/generate-org-data.test.ts.snap

Change: 
- orgs 👉 organizations
- org 👉 organization

chore: correct to american spelling orgs => organizations

---

docs/import.md
src/cmds/list:imported.ts
src/lib/types.ts
src/scripts/generate-imported-targets-from-snyk.ts
test/scripts/generate-imported-targets-from-snyk.test.ts
test/system/__snapshots__/generate-imported-targets-from-snyk.test.ts.snap

Added the option to generate import target log file also for GCR

feat: generate imported targets for GCR

---

src/loggers/log-failed-projects.ts

fix: log failed projects filenames

---

package.json

Fixes the type error:  Property 'POST /repos/{owner}/{repo}/forks' does not exist on type 'Endpoints'.

fix: use latest version to fix type errors

---

test/system/list:imported.test.ts

chore: bump-test-timeout

---

src/lib/types.ts

With the "critical" severity coming out, added a one-liner to the types.ts file to support that
Need to add support to the new "critical" severity

chore: Updated types to include support for the new critical severity

---

.gitignore
package.json
test/scripts/__mocks__/snyk-request-manager.ts
test/scripts/create-orgs.test.ts
test/system/help.test.ts
test/system/import.test.ts
test/system/list:imported.test.ts
test/system/orgs:create.test.ts
test/system/orgs:data.test.ts

Upgrade build & test related deps to latest versions

chore: bump dependency versions to latest

---

docs/import.md

Improve the docs to explain better `exclusionGlobs` & `files`
Add example for GCR import

docs: Update import docs to clarify target, exclusion globs and files

---

docs/import.md

Update the import docs to include ECR example & a disclaimer that this tool has 100% support for import API

docs: include ECR example and a disclaimer on support

---

src/cmds/list:imported.ts
src/lib/types.ts
src/scripts/generate-imported-targets-from-snyk.ts
test/scripts/generate-imported-targets-from-snyk.test.ts

Adds support of the list:import command to include Azure repos

feat: list imported for Azure

---

src/cmds/orgs:create.ts
src/cmds/orgs:data.ts
src/lib/api/group/index.ts
src/scripts/create-orgs.ts

add the missing `!` for boolean assertion not for value check 😢  + add more debug to show progress

fix: correctly check statusCode is present on orgs:create

---

src/lib/api/group/index.ts
src/lib/api/org/index.ts
src/scripts/create-orgs.ts

Fix the expected 2xx codes as we now actually end up checking them

fix: check for the relevant 2xx code

---

package.json

Use latest version of `snyk-request-manager` that pins Axios as the package keeps releasing breaking changes without a major version bump

feat: upgrade snyk-request-manager to 1.4.3

---

README.md

tiny doc update to mention broker support as this question comes up sometimes.

docs: add FAQ entry for brokered integrations

---

README.md

Link to releases & npm package as part of installation instructions

docs: include installation instructions

---

package.json
src/cmds/orgs:create.ts
src/lib/api/poll-import/index.ts
src/lib/source-handlers/github/index.ts
src/loggers/log-failed-org.ts
src/scripts/create-orgs.ts
src/scripts/import-projects.ts
test/lib/get-import-path.spec.ts
test/lib/orgs.test.ts
test/lib/source-handlers/azure/azure.test.ts
test/lib/source-handlers/github/github.test.ts
test/scripts/create-orgs.test.ts
test/scripts/generate-targets-data.test.ts
test/scripts/import-projects.test.ts
test/system/__snapshots__/help.test.ts.snap
test/system/__snapshots__/import:data.test.ts.snap
test/system/__snapshots__/list:imported.test.ts.snap
test/system/__snapshots__/orgs:data.test.ts.snap
test/system/import.test.ts
test/system/list:imported.test.ts
test/system/orgs:create.test.ts
test/unit/scripts/import-projects.test.ts

Updating the packages.json file to run all tests and to format all files when running the "npm test" and "npm run format" commands.

fix: enable tests & formatting 

---

package.json

Bump snyk-request-manager to 1.4.4 which fixes the HTTPS axios proxy bug with mcaffee proxy https://github.com/snyk-tech-services/snyk-request-manager/pull/49
Fixes https://github.com/snyk-tech-services/snyk-api-import/issues/272
- https://github.com/snyk-tech-services/snyk-request-manager/pull/49

fix: https mcaffee axios proxy bug

---

package.json
test/lib/source-handlers/github/github.test.ts
test/scripts/generate-org-data.test.ts
test/scripts/generate-targets-data.test.ts

Bump to latest version of `snyk-request-manager` that reduces open handles

fix: reduce open file handles in snyk-request-manager

---

src/lib/api/import/index.ts

Skip retrying if we received back a `404`

fix: do not retry 404s + reduce retry count

---

src/lib/limiters.ts
src/lib/request-with-rate-limit.ts
src/lib/source-handlers/azure/list-projects.ts
src/lib/source-handlers/azure/list-repos.ts
src/lib/source-handlers/bitbucket-server/list-projects.ts
src/lib/source-handlers/bitbucket-server/list-repos.ts
test/lib/request-with-rate-limit.test.ts

- Moved handling responses fro needle, including 429, to an external function
- Changed Azure scripts to work with new function
- Added some tests for the new function
Need some advise on the tests
- [Jira ticket](https://snyksec.atlassian.net/browse/TECHSERV-1714)

feat: handle 429 responses

---

src/lib/api/group/index.ts
test/scripts/import-projects.test.ts

Change the 'create org' endpoint to use to documented one (/orgs)

fix: change org creation endpoint

---

docs/import-data.md
docs/orgs.md

Added info regarding Bitbucket Cloud to the import:data doc

docs: update import doc with bitbucket cloud info

---

test/lib/generate-target-ids.test.ts
test/system/help.test.ts
test/system/import.test.ts
test/system/import:data.test.ts
test/system/list:imported.test.ts
test/system/orgs:create.test.ts
test/system/orgs:data.test.ts

Assert current exit codes, before looking at potentially introducing more exit code types.

test: assert expected exit codes

---

src/cmds/import:data.ts
test/system/import:data.test.ts

exit code 1 if `import:data` errors

fix: exit code 1 if `import:data` errors

---

.circleci/config.yml

Upgrade snyk/orb to fix a download issues of the CLI

fix: upgrade snyk/scan orb to fix pipeline

---

src/lib/api/import/request-with-rate-limit.ts

Skip retrying `/import` API calls to accept import on 404s & 504s. If the request timed out it is unclear if it was accepted or not, assume this failed for log purposes.

feat: skip retrying 504s - Timed out waiting for response

---

src/cmds/orgs:create.ts
src/lib/types.ts

Refactor org:create command.
Move the code to a specific function that returns a filename.
Filename is not use at the moment.

feat: refactoring org create command

---

src/cmds/list:imported.ts
src/lib/types.ts

- [] Tests written and linted [ℹ︎](https://github.com/snyk-tech-services/general/wiki/Tests)
Refactor list:imported command, mode the code in a function to return a filename.
https://www.notion.so/snyk/snyk-api-import-mirror-command-7d182dcc68d94c5f88c0b78ddad9d880

feat: refactor list:imported command

---

src/cmds/orgs:data.ts

refactor OrgData, move the code in a function to be used in mirror command

feat: refactor orgs data

---

README.md
docs/import.md

Improve docs around import & analysing logs

docs: mention how to analyse logs

---

README.md
docs/import.md
src/lib/api/import/index.ts
src/lib/api/poll-import/index.ts

Updating all references to the import endpoint in Snyk docs with the new link

feat: update docs with new api link

---

src/cmds/import.ts
src/loggers/log-imported-batch.ts
src/scripts/import-projects.ts
test/scripts/import-projects.test.ts

feat: refactor import command

---

src/cmds/import.ts

fix the error message for the import command

fix: correct the import message error

---

src/stream-data.ts
test/lib/fixtures/create-orgs/1-org/1-org-minified.json
test/lib/fixtures/create-orgs/1-org/1-org-prettified.json
test/lib/stream-data.spec.ts
test/scripts/generate-targets-data.test.ts
test/scripts/import-projects.test.ts

Add tests to `streamData` and fix a bug where huge prettified JSON was not being parsed.

fix: process large prettified JSON successfully

---

src/lib/source-handlers/azure/list-repos.ts
test/lib/source-handlers/azure/azure.test.ts

Allow project to be fetched by id for azure repo.

feat: use project id to list Azure repos

---

README.md

mark this repo as actively maintained

docs: mark as maintained

---

src/lib/api/org/index.ts
src/lib/types.ts
test/lib/__snapshots__/org.test.ts.snap
test/lib/org.test.ts
test/system/orgs.test.ts

Implement get target from v3 api for the full sync feature work.
- [TECHSERV-3368](https://snyksec.atlassian.net/jira/software/c/projects/TECHSERV/boards/387?modal=detail&selectedIssue=TECHSERV-3368)

feat: implements get target per org + test

---

src/lib/project/compare-branches.ts
test/lib/projects.test.ts

Create a function to update a project branch if needed.
- [TECHSERV-3372](https://snyksec.atlassian.net/jira/software/c/projects/TECHSERV/boards/387?modal=detail&selectedIssue=TECHSERV-3372)

feat: compare and update branches

---

src/lib/api/org/index.ts
src/lib/types.ts
test/lib/org.test.ts

Fix the fall back next link to be relative path only, we will not receive a full path and can't assume the snyk host.
Also formatting the file, it was not formatted somehow.
Renaming anything vars that had a capital letter, this is reserved for Classes and Interfaces
Fix the return type to be `SnykTarget[]` instead of `RESTTargetResponse`

fix: update targetAPI pagination

---

.eslintrc.json

Update the rule for all filenames to be kebab case.

chore: update filename rule

---

src/common.ts
src/loggers/log-updated-project.ts

Log projects that had their branch updated & introduce filename for it

chore: log updated projects

---

src/lib/source-handlers/github/get-default-branch.ts
src/scripts/generate-imported-targets-from-snyk.ts

- Change the input for get default branch to be snyk target
- export project converters & type imports

refactor: default branch call

---

.prettierignore
package.json
src/cmds/import.ts
src/cmds/import:data.ts
src/cmds/list:imported.ts
src/cmds/orgs:create.ts
src/cmds/orgs:data.ts
src/lib/api/feature-flags/index.ts
src/lib/api/org/index.ts
src/lib/api/poll-import/index.ts
src/lib/project/update-branch.ts
src/lib/source-handlers/azure/list-repos.ts
src/lib/source-handlers/bitbucket-cloud/list-repos.ts
src/lib/source-handlers/bitbucket-cloud/list-workspaces.ts
src/lib/source-handlers/bitbucket-server/list-projects.ts
src/lib/source-handlers/bitbucket-server/list-repos.ts
src/scripts/create-orgs.ts
src/scripts/generate-imported-targets-from-snyk.ts
src/scripts/generate-org-data.ts
src/scripts/generate-targets-data.ts
src/scripts/sync/sync-org-projects.ts
src/scripts/sync/sync-projects-per-target.ts
test/lib/import-projects.test.ts
test/lib/org.test.ts
test/scripts/generate-imported-targets-from-snyk.test.ts
test/scripts/generate-targets-data.test.ts
test/scripts/sync/sync-org-projects.test.ts
test/system/list:imported.test.ts
test/unit/scripts/import-projects.test.ts

chore: prettier formatting

---

src/scripts/sync/generate-projects-diff-actions.ts
test/scripts/sync/generate-projects-diff-actions.spec.ts

Function that compares file paths found in repo and Snyk projects to compare the diff in a repo.

feat: function to find repo files diff

---

src/scripts/sync/sync-projects-per-target.ts

refactor to grab repo meta earlier and pass it into each update function

refactor: get repo meta data early

---

src/lib/supported-project-types/supported-manifests.ts
src/loggers/log-failed-to-update-projects.ts
src/loggers/log-updated-project.ts
src/scripts/sync/clone-and-analyze.ts
src/scripts/sync/generate-projects-diff-actions.ts
test/lib/supported-project-types/index.test.ts
test/scripts/sync/clone-and-analyze.spec.ts
test/scripts/sync/generate-projects-diff-actions.spec.ts

Add support for comparing discovered files vs projects given a list of ecosystems to investigate

Fix: ecosystem aware filtering

---

src/lib/api/org/index.ts
src/lib/supported-project-types/supported-manifests.ts
src/lib/types.ts
test/lib/__snapshots__/org.test.ts.snap
test/lib/supported-project-types/index.test.ts
test/scripts/sync/clone-and-analyze.spec.ts
test/scripts/sync/generate-projects-diff-actions.spec.ts
test/scripts/sync/sync-org-projects.test.ts

Refactor `getSCMSupportedManifests` to check for empty array as well as not set

chore: refactor `getSCMSupportedManifests`

---

src/lib/supported-project-types/supported-manifests.ts
src/scripts/sync/clone-and-analyze.ts
test/lib/supported-project-types/index.test.ts
test/scripts/sync/clone-and-analyze.spec.ts

Add entitlement for Open Source so products discovered can be fully controlled

refactor: add implied os entitlement

---

src/cmds/sync.ts
src/lib/api/project/index.ts
src/scripts/create-orgs.ts
src/scripts/generate-imported-targets-from-snyk.ts
src/scripts/import-projects.ts
src/scripts/sync/sync-org-projects.ts

Fix logging string and provide command context to the API calls

feat: better api call marking

---

src/scripts/sync/sync-projects-per-target.ts

Dedupe projects before logging

fix: dedupe projects before logging

---

src/scripts/sync/clone-and-analyze.ts

Search for manifests 10 folders deep instead of 6

feat: look for files 10 levels deep

---

test/scripts/fixtures/import-projects-gitlab.json
test/scripts/import-projects.test.ts

Fix & enable Gitlab import test

test: enable gitlab import test

---

test/system/sync.test.ts

Update test assertion back to what it should have been

test: fix number of targets processed

---

package.json
src/lib/source-handlers/github/get-repo-metadata.ts
src/lib/source-handlers/github/list-organizations.ts
src/lib/source-handlers/github/list-repos.ts
src/lib/source-handlers/github/organization-is-empty.ts
test/system/orgs:data/gitlab.test.ts

Enable Github API retries by using the retry plugin.

feat: enable Github API retries x 3

---

docs/import.md
docs/sync.md

Update docs on which logs `sync`  will generate

docs: sync-logs

---

test/scripts/import-projects.test.ts
test/system/orgs:data/gitlab.test.ts

Bump timeouts to reduce flakiness

test: increase flaky test timeouts

---

.github/CODEOWNERS

chore: update team owners

---

docs/sync.md

Removed 'Gitlab' from ## Branches

---

src/lib/source-handlers/github/list-repos.ts

Log archived github repos in debug mode

feat: log archived Github repos

---

test/lib/git-clone.spec.ts
test/lib/source-handlers/github/github.test.ts
test/scripts/create-orgs.test.ts
test/scripts/generate-org-data.test.ts
test/scripts/generate-targets-data.test.ts
test/scripts/sync/clone-and-analyze.spec.ts
test/system/list:imported.test.ts

drop contex var in favour of specific one to this project

chore: drop gh token var

---

package.json
src/lib/git-clone.ts
src/scripts/sync/clone-and-analyze.ts
test/lib/git-clone.spec.ts
test/scripts/generate-targets-data.test.ts
test/scripts/sync/clone-and-analyze.spec.ts

retry deleting cloned repos up to 3 times.

feat: retry deletion 3 times

---

src/scripts/sync/clone-and-analyze.ts
src/scripts/sync/generate-projects-diff-actions.ts
src/scripts/sync/sync-projects-per-target.ts
test/scripts/sync/clone-and-analyze.spec.ts
test/scripts/sync/generate-projects-diff-actions.spec.ts

chore: rename deactivate to remove

---

.circleci/config.yml

Remove noise to slack channels.

Remove notifications to slack on pipeline failure

---

package.json

Bumps snyk-request-manager to proxy request properly, using CONNECT method, disabling axios built-in flawed proxy support.

fix: bump snyk req manager for proxy fix

---

.snyk

There is no path to fixing this vuln yet.

chore: add snyk ignore for inflight vuln

---

.circleci/config.yml
.releaserc
README.md
docs/example-workflows/aws-automation-example.md
docs/import-data.md
docs/import.md
docs/mirror-bitbucket-cloud.md
docs/mirror-bitbucket-server.md
docs/mirror-github.md
docs/mirror-gitlab.md
docs/orgs.md
docs/sync.md
jest.config.js
package.json

This uses a new version of `snyk-request-manager` to fix vulnerabilities in axios.
Standalone binaries have been removed from the the release due to problems generating them using `nexe`.

Fix: axios vulnerabilities [IM-55]

---

.releaserc

Just tweaks the .releaserc file to hopefully correct the release process.

fix: adjust releaserc

---

.circleci/config.yml
src/lib/find-files.ts
src/scripts/sync/clone-and-analyze.ts

fix: Circle config update, add prodsec orb scans

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/example-workflows/aws-automation-example.md
docs/import.md
docs/sync.md
package.json
test/lib/source-handlers/github/github.test.ts

chore: update repo URL and CODEOWNERS [IM-SEC]

---

catalog-info.yaml

Adds `catalog-info.yaml` file for Team Import.

chore: add catalog-info file [IM-121]

---

.circleci/config.yml
package.json

Locks Lodash types package version to prevent build errors with latest versions (since 4.17.6).
Adds Slack notifications on future main pipeline failures.

fix pipeline

---

README.md
package.json

Adding the supported Node version to README.

docs: add supported Node version to README
