snyk/snyk-api-import

src/lib/group/index.ts, src/lib/org/index.ts, src/scripts/create-orgs.ts, test/lib/orgs.test.ts, test/scripts/import-projects.test.ts
- Disable all notifications we can by default for a new org.
- Use request manager for org creation
- Export the import orgs script to make it easier to run
=> feat: disable all notifications for new orgs by default

README.md
Fixes an issue where the badge referenced an old repo belonging to the Snyk GitHub organisation. 
- [Jira ticket SC-0000](https://snyksec.atlassian.net/browse/SC-0000)
- [Link to documentation](https://github.com/snyk/snyk-api-import/wiki/)
=> docs: correct URL in badge

src/lib/get-logging-path.ts, test/scripts/import-projects.test.ts
Create the logging directory if we can when the path provided doesn't yet exist https://github.com/snyk-tech-services/snyk-api-import/issues/49
=> feat: create the log folder if it is missing

src/scripts/import-projects.ts
Count the imported targets in *all* possible targets for counter pruposes
=> fix: imported targets number to include skipped

package.json, src/lib/import/index.ts, src/scripts/create-orgs.ts, test/lib/index.test.ts, test/lib/orgs.test.ts
Use latest requests manager that creates user-agent for logging purposes
=> feat: use latest snyk-request-manager with user-agent

package.json, src/scripts/github/list-orgs.ts, src/scripts/github/list-repos.ts, test/scripts/github.test.ts
Introduce oktokit & ability to fetch orgs & repos to be used later to generate import data.
=> feat: introduce octokit to fetch Github repos & orgs

README.md, package.json, src/cmds/import.ts, src/index.ts, test/system/__snapshots__/basic.test.ts.snap, test/system/basic.test.ts
Introduce `yargs` to help manage multiple commands, set the import to be default and run when no command is provided for backwards compatibility.
=> feat: introduce yargs & set default command for backwards compatability

src/common.ts, test/scripts/import-projects.test.ts
Drop unused log name variable `IMPORT_PROJECTS_FILE_NAME`
=> chore: drop unused log name variable IMPORT_PROJECTS_FILE_NAME

src/lib/import/index.ts, src/lib/poll-import/index.ts, src/scripts/import-projects.ts, test/lib/index.test.ts
Use request manager to poll urls as well
=> feat: user request manager for polling urls

README.md, docs/import.md, docs/orgs.md, src/cmds/orgs:data.ts, src/index.ts, src/lib/types.ts, src/scripts/create-orgs.ts, src/scripts/generate-org-data.ts, src/scripts/github/index.ts, src/scripts/github/list-orgs.ts, src/write-file.ts, test/delete-files.ts, test/lib/index.test.ts, test/scripts/generate-org-data.test.ts, test/scripts/import-projects.test.ts, test/scripts/polling.test.ts, test/system/__snapshots__/basic.test.ts.snap, test/system/__snapshots__/generate-org-data.test.ts.snap, test/system/generate-org-data.test.ts, test/system/import.test.ts
- Provide a utility to help generate mirror data for Github orgs
to be mirrored in Snyk.
- re-arrange the docs as they are now growing quite a bit
=> feat: generate org data for Github.com

.gitignore, README.md, src/common.ts, src/lib/import/index.ts, src/lib/poll-import/index.ts, src/log-job-result.ts, src/scripts/import-projects.ts, test/generate-log-file-names.ts, test/lib/index.test.ts, test/scripts/fixtures/empty-target/import-projects.json, test/scripts/fixtures/no-supported-manifests/import-projects.json, test/scripts/import-projects.test.ts
- Log the entire response on completion of a job
- Add a test for processing an empty repo to show expected behaviour (import complete with no projects returned)
=> feat: log full import job status & test empty repo

src/log-imported-projects.ts, test/lib/index.test.ts, test/scripts/import-projects.test.ts, test/scripts/polling.test.ts, test/system/import.test.ts
The log message was accidentally saying the opposite on successful project import
=> fix: imported project message to reflect "import"

docs/orgs.md, src/cmds/orgs:data.ts, src/scripts/generate-org-data.ts, src/scripts/github/list-orgs.ts, test/scripts/github.test.ts, test/system/__snapshots__/generate-org-data.test.ts.snap
Set a default github.com url for github API calls
=> feat: support github enterprise with github.com being a default

src/scripts/github/github-base-url.ts, src/scripts/github/list-orgs.ts, src/scripts/github/list-repos.ts, test/scripts/github.test.ts
Add support for GHE when listing repos too in preparation for generating the import data
=> feat: support GHE base url when lising repos

docs/orgs.md, src/cmds/orgs:data.ts, src/scripts/generate-org-data.ts, src/scripts/github/list-orgs.ts, test/scripts/generate-org-data.test.ts, test/system/__snapshots__/generate-org-data.test.ts.snap
Keep source types the same as integration types to reduce any confusion while generated import data.
=> feat: separate github-enterprise as a source type

docs/orgs.md
Update the docs to reference the correct `GITHUB_TOKEN` variable name
=> fix: GH_TOKEN should be GITHUB_TOKEN in docs

src/scripts/github/list-orgs.ts
Oktokit does not follow pages by default, adding in paginated calls manually.
=> fix: use pagination for listing gh orgs

README.md, docs/import-data.md, src/cmds/import.ts, src/cmds/import:data.ts, src/lib/poll-import/index.ts, src/lib/types.ts, src/scripts/create-orgs.ts, src/scripts/generate-org-data.ts, src/scripts/generate-targets-data.ts, src/scripts/github/index.ts, src/scripts/github/list-orgs.ts, src/scripts/github/list-repos.ts, test/scripts/generate-targets-data.test.ts, test/system/__snapshots__/basic.test.ts.snap
Utility to help generate Import Data from Github & Github Enterpise to be used during `import` command. This is *opinionated* and assumes user wants a *mirror* of their GH / GHE orgs in Snyk with the corresponding repos underneath.
=> feat: generate targets import data based on Snyk Org data

src/lib/org/index.ts, test/lib/orgs.test.ts
Make sure all settings are disabled by setting the type to `none`
=> feat: disable vuln settings on org creation

.circleci/config.yml
use npm install instead of ci since there is no lock.
=> fix: use npm i instead of ci

.releaserc, package.json, src/lib/org/index.ts, test/lib/orgs.test.ts
Horrible HACK for now as no other work around could be found at this time to remove the problem type file before running pkg as it prevents the error & ends up building a valid working binary.
=> fix: HACK - drop problem type file before pkg

.releaserc
Missed `rm` in a command to delete problem file
=> fix: fix typo - missed `rm` in the hack command

.releaserc
Try removing the types just before to avoid the ts error
=> fix: only drop type just before pkg

.releaserc
Fix a type & close the quote for nexe files pattern
=> fix: close quote on nexe extra files pattern

.releaserc
Release linux as 64bit binary, migrating to nexe introduced a bug and caused 32bit to be released instead.
=> fix: ensure linux binary is 64bit

test/scripts/create-orgs.test.ts, test/scripts/fixtures/create-orgs/1-org/1-org.json, test/scripts/import-projects.test.ts
The import API now sends userMessage on project failures, expect this.
=> test: Update test assertion to expect userMessage on failed projects

src/common.ts, src/generate-target-id.ts, src/lib/import/index.ts, src/lib/poll-import/index.ts, src/lib/types.ts, src/loggers/log-created-org.ts, src/loggers/log-failed-imports.ts, src/loggers/log-failed-org.ts, src/loggers/log-failed-polls.ts, src/loggers/log-failed-projects.ts, src/loggers/log-import-jobs.ts, src/loggers/log-imported-batch.ts, src/loggers/log-imported-projects.ts, src/loggers/log-imported-targets.ts, src/loggers/log-job-result.ts, src/scripts/create-orgs.ts, src/scripts/import-projects.ts, test/lib/import-projects.test.ts
- add tests to ensure targets are correctly skipped
- move all logging utils into logging folder
- update generate target ID functionality to only pick out supported target fields
=> feat: refactor generate target ID

.releaserc, package.json
https://github.com/nexe/nexe/issues/755
Latest beta nexe version stopped working as expected, pinning to previously working version.
=> feat: pin nexe to older working version

docs/import.md, src/cmds/import:data.ts, src/cmds/list:imported.ts, src/cmds/orgs:data.ts, src/lib/types.ts, src/scripts/generate-imported-targets-from-snyk.ts, src/scripts/generate-org-data.ts, src/scripts/generate-targets-data.ts, test/scripts/generate-imported-targets-from-snyk.test.ts, test/scripts/generate-org-data.test.ts, test/scripts/generate-targets-data.test.ts, test/system/__snapshots__/generate-imported-targets-from-snyk.test.ts.snap
Allow the list:imported command to also convert Bitbucket Cloud
projects into "imported targets" so they can be skipped
=> feat: support to skip Bitbucket Cloud projects during re-import

docs/import.md, src/cmds/list:imported.ts, src/scripts/generate-imported-targets-from-snyk.ts, test/scripts/generate-imported-targets-from-snyk.test.ts, test/system/__snapshots__/generate-imported-targets-from-snyk.test.ts.snap, test/system/generate-imported-targets-from-snyk.test.ts
Allow user to target a specific organization when listing imported targets
=> feat: list imported targets for specific org

docs/import.md, src/cmds/list:imported.ts, src/lib/api/import/index.ts, src/loggers/log-imported-targets.ts, src/scripts/generate-imported-targets-from-snyk.ts, test/scripts/generate-imported-targets-from-snyk.test.ts, test/system/__snapshots__/generate-imported-targets-from-snyk.test.ts.snap, test/system/generate-imported-targets-from-snyk.test.ts
Allow listing projects in Snyk for multiple integration types that are provides like so: 
```
snyk-api-import list:imported --integrationType=github --integrationType=github-enterprise --groupId=<groun_id>
```
=> feat: allow multiple integration types to list imported projects

docs/import.md, src/cmds/list:imported.ts, src/lib/types.ts, src/scripts/generate-imported-targets-from-snyk.ts, test/system/__snapshots__/generate-imported-targets-from-snyk.test.ts.snap
Add support for `docker-hub` in `list:imported` command
=> feat: add support for generating target also for docker-hub

src/lib/api/poll-import/index.ts, src/loggers/log-failed-projects.ts, test/scripts/import-projects.test.ts
Reduce open handles by logging all projects once at the end and creating 1 logger per org.
=> fix: reduce open handles when logging failed projects

src/cmds/orgs:create.ts, src/lib/api/org/index.ts, src/lib/filter-out-existing-orgs.ts, src/scripts/create-orgs.ts, test/lib/org.test.ts, test/lib/orgs.test.ts, test/scripts/create-orgs.test.ts, test/system/__snapshots__/help.test.ts.snap, test/system/__snapshots__/orgs:create.test.ts.snap
When generating org data for a full repo sync include the data for existing organisations as well so it is easy to create the needed import data for them.
This can be optionally disabled via `--includeExistingOrgsInOutput=false`
=> feat: log existing orgs data

docs/import-data.md, package.json, src/cmds/import:data.ts, src/cmds/orgs:data.ts, src/lib/index.ts, src/lib/source-handlers/github/index.ts, src/lib/source-handlers/gitlab/get-base-url.ts, src/lib/source-handlers/gitlab/get-token.ts, src/lib/source-handlers/gitlab/index.ts, src/lib/source-handlers/gitlab/list-repos.ts, src/lib/source-handlers/gitlab/types.ts, src/lib/types.ts, src/scripts/generate-org-data.ts, src/scripts/generate-targets-data.ts, test/lib/source-handlers/github/github.test.ts, test/lib/source-handlers/gitlab/list-repos.test.ts, test/scripts/generate-org-data.test.ts, test/scripts/generate-targets-data.test.ts, test/system/__snapshots__/import:data.test.ts.snap, test/system/fixtures/org-data/orgs.json, test/system/help.test.ts, test/system/import.test.ts, test/system/import:data.test.ts, test/system/list:imported.test.ts, test/system/orgs:create.test.ts, test/system/orgs:data.test.ts, tsconfig.json
- Add suport for Gitlab projects to be listed given a Group
- Generate the targets data needed for Snyk to import the projects
Support for generating Gitlab Import data, docs to read & review https://github.com/snyk-tech-services/snyk-api-import/blob/2731790dcda3e97e226cc59a32d97e52e43f4cec/docs/import-data.md
=> feat: support Gitlab for import repo data generation

docs/import-data.md, docs/orgs.md, src/lib/source-handlers/github/organization-is-empty.ts, src/lib/source-handlers/gitlab/group-is-empty.ts, src/lib/source-handlers/gitlab/index.ts, src/lib/source-handlers/gitlab/list-groups.ts, src/lib/source-handlers/gitlab/types.ts, src/lib/types.ts, src/scripts/generate-org-data.ts, test/lib/source-handlers/gitlab/list-groups.test.ts, test/scripts/generate-org-data.test.ts, test/system/__snapshots__/orgs:data.test.ts.snap, test/system/orgs:data.test.ts
List all Groups in Gitlab and transform the data to the format needed for Snyk to create the organizations. This is part of the `mirror` workflow have the same structure in Snyk as in Gitlab where:
- Gitlab Group = Snyk Organization
- Gitlab Project within the group = Snyk Project within the group
Docs: https://github.com/snyk-tech-services/snyk-api-import/blob/b1b29396114f76f27d49527d41af91b1f3d7baed/docs/orgs.md
=> feat: support listing all available Gitlab Groups

docs/import.md, src/cmds/import.ts, src/lib/get-import-path.ts, test/lib/fixtures/single-project/import-projects-single.json, test/lib/fixtures/single-project/import-projects.json, test/lib/get-import-path.spec.ts
Support absolute and relative path to the import file,
if only a folder path is provided assume a default file name
Allow users to provide the path via --file param as well as the
env variable
https://github.com/snyk-tech-services/snyk-api-import/issues/192
=> feat: improve import file location

src/scripts/import-projects.ts, test/scripts/import-projects.test.ts
Rather than just display "Failed to parse targets from <file>" also
include the JSON.parse error message to help detect where the issue is
=> fix: forward on full JSON.parse error to user

src/scripts/create-orgs.ts, src/scripts/import-projects.ts, src/stream-data.ts
Migrate to using streams for loading orgs file as well, support both minified and beautified format json
=> fix: use streams for org json loading

test/generate-target-ids.test.ts
test existing logic that generates the target ids for matching targets before making changes to this logic for Gitlab so we have a baseline behaviour
=> test: assert expected targetIds per supported project origin

src/lib/api/import/index.ts
Increment attempts in the correct place so we don't end up for ever retrying for non 429 errors.
Exit the whole process instead of return when every batch fails.
=> fix: increment retry count on all failures not just rate limiting

src/lib/api/import/index.ts, src/lib/get-import-path.ts, src/scripts/import-projects.ts, src/stream-data.ts
Some of the errors for 401 & missing required target json keys were coming back to the user uncaught/sanitized. Adding a fix for this
Before we would show a type error, now we show the correct error bubbled up for bad auth:
Before
Now
=> fix: improve error handling & messages when received 401

src/lib/api/group/index.ts, src/lib/api/import/index.ts, src/lib/api/org/index.ts, src/lib/api/poll-import/index.ts, src/lib/api/project/index.ts, src/scripts/import-projects.ts
Fix [a bug](https://github.com/snyk-tech-services/snyk-api-import/pull/243/files#diff-c24486035bedf2797b3c0daba7cad3100f8504453a264262789a0131085f4411R57) that is treating successful imports as fails & add more logging. Reduce retry count as we retry also based on the error code in the backend and in the tool
=> fix: check for correct status code prop name  before failing import

src/cmds/import.ts, src/lib/get-import-path.ts
Respect the SNYK_IMPORT_PATH variable when set, at the moment `--file` overrides it always.
=> fix: respect the SNYK_IMPORT_PATH variable when set

src/lib/api/import/index.ts
Bump the rate limited triggered sleep to make it cover a max of ~1hr
=> fix: increase sleep duration when rate limiting error seen

src/lib/api/org/index.ts
GET projects is expected to return a `200` not `201`
=> fix: expect 200 on GET projects

src/lib/source-handlers/azure/list-projects.ts, src/lib/source-handlers/azure/list-repos.ts, test/lib/source-handlers/azure/azure.test.ts
Adds try/catch to the azure calls to catch failed calls.
[Jira Ticket](https://snyksec.atlassian.net/browse/TECHSERV-1680)
=> fix: add catch to azure api calls and resturcture functions

docs/import-data.md, docs/orgs.md, src/cmds/import:data.ts, src/lib/index.ts, src/lib/source-handlers/bitbucket-server/get-bitbucket-server-token.ts, src/lib/source-handlers/bitbucket-server/index.ts, src/lib/source-handlers/bitbucket-server/list-projects.ts, src/lib/source-handlers/bitbucket-server/list-repos.ts, src/lib/source-handlers/bitbucket-server/project-is-empty.ts, src/lib/source-handlers/bitbucket-server/types.ts, src/lib/types.ts, src/scripts/generate-org-data.ts, src/scripts/generate-targets-data.ts, test/lib/source-handlers/bitbucket-server/bitbucket-server.test.ts, test/lib/source-handlers/github/github.test.ts, test/scripts/generate-org-data.test.ts, test/system/__snapshots__/import:data.test.ts.snap, test/system/__snapshots__/orgs:data.test.ts.snap, test/system/import:data.test.ts, test/system/orgs:data.test.ts
Adds support for the import:data command to Bitbucket Server
=> feat: `import:data` and `org:data` commands for bitbucket server

docs/mirror-bitbucket-server.md
Adds a mirroring document for Bitbucket Server for when all the commands are approved
=> feat: add mirror doc for bitbucket server

src/scripts/create-orgs.ts, test/scripts/create-orgs.test.ts, test/system/orgs:create.test.ts
Fix for a bug that was preventing existing orgs to be written to file of no orgs were created.
=> fix: write existing orgs file if asked

src/cmds/import:data.ts, src/cmds/orgs:data.ts, src/lib/index.ts, src/lib/request-with-rate-limit.ts, src/lib/source-handlers/azure/list-projects.ts, src/lib/source-handlers/azure/list-repos.ts, src/lib/source-handlers/bitbucket-cloud/get-bitbucket-cloud-password.ts, src/lib/source-handlers/bitbucket-cloud/get-bitbucket-cloud-username.ts, src/lib/source-handlers/bitbucket-cloud/index.ts, src/lib/source-handlers/bitbucket-cloud/list-repos.ts, src/lib/source-handlers/bitbucket-cloud/list-workspaces.ts, src/lib/source-handlers/bitbucket-cloud/types.ts, src/lib/source-handlers/bitbucket-cloud/workspace-is-empty.ts, src/lib/source-handlers/bitbucket-server/list-projects.ts, src/lib/source-handlers/bitbucket-server/list-repos.ts, src/lib/types.ts, src/scripts/generate-targets-data.ts, test/lib/request-with-rate-limit.test.ts, test/lib/source-handlers/bitbucket-cloud/bitbucket-cloud.test.ts, test/lib/source-handlers/bitbucket-server/bitbucket-server.test.ts, test/system/__snapshots__/import:data.test.ts.snap, test/system/__snapshots__/orgs:data.test.ts.snap, test/system/fixtures/org-data/bitbucket-cloud-orgs.json, test/system/import:data.test.ts
Support for Bitbucket Cloud in `import:data` command to help generate the targets data needed to kick off import.
This will list all repos in the given orgs (provided in the orgs data file) to be imported into the matching orgs in Snyk
=> feat: `import:data` command for Bitbucket Cloud

src/lib/api/import/index.ts
The failed targets are logged twice today as we already do this here: https://github.com/snyk-tech-services/snyk-api-import/blob/57b9d225b8133b9fd6934c3b9562ef7ea00c5cc6/src/lib/api/import/index.ts#L148
=> fix: remove extraneous imported target logging

src/lib/request-with-rate-limit.ts, test/lib/request-with-rate-limit.test.ts
Encode the url before sending the requests. This will allow repos name with icons, Chinese characters....
=> fix: sanitise url for getrepos

src/cmds/list:imported.ts, src/lib/api/org/index.ts, src/scripts/generate-imported-targets-from-snyk.ts, test/lib/generate-target-ids.test.ts, test/scripts/generate-imported-targets-from-snyk.test.ts
- reduce the # of tests as they cover much of the same area
- combine some of the GHE tests
- move the target id test into test/lib
- filter projects by origin if a single origin aka type is provided to the `list:imported` command, list all if more than one is provided
=> fix: filter projects to origin if a single one provided

src/cmds/orgs:data.ts, test/system/orgs:data/errors.test.ts
Manually set exit code 1 is `orgs:data` command errors.
=> fix: exit code 1 if `orgs:data` errors

README.md
- Document how to set signed certificate path for API calls to SCM
- Document that 100% of API import sources are supported for `import`
=> docs: set signed certificate path for API calls to SCM

src/cmds/orgs:create.ts, src/loggers/log-failed-org.ts, src/scripts/create-orgs.ts, test/lib/org.test.ts, test/system/orgs:create.test.ts
Ensure exit code 1 when all orgs fail to create
=> feat: exit code 1 if all orgs fail to create

docs/orgs.md
Some words were missing from the description of what the parameters do and this lead to organising that section to have a more practical order of parameters and correct an incorrect link to the apiary API docs.
Read it
n/a
Imagine a picture of a small kitten drinking milk at 3:30am.
=> docs: improve readme and corect incorrect link for orgs readme

src/lib/source-handlers/bitbucket-cloud/list-repos.ts, src/lib/source-handlers/bitbucket-cloud/list-workspaces.ts
Improves the BBC API calls to send less calls that fetch more data each by adding the `pagelen` var into the calls
=> feat: improve bitbucket cloud api calls

src/lib/source-handlers/gitlab/list-repos.ts, test/lib/source-handlers/gitlab/list-repos.test.ts
Filters Gitlab projects that are shared with other groups
- [Slack Thread](https://snyk.slack.com/archives/C010RJA3205/p1651153164796579)
- [Jira Ticket](https://snyksec.atlassian.net/browse/TECHSERV-1866)
=> feat: filter gitlab projects that are shared

src/lib/source-handlers/gitlab/list-repos.ts
Filter out Gitlab projects that do not yet have a branch (aka the repo is empty)
=> fix: filter out Gitlab projects without branch

src/lib/api/import/index.ts, test/lib/import-projects.test.ts
Target sent to Snyk APIs is always sanitized by default.
=> fix: always send danitized target

docs/import-data.md, src/lib/source-handlers/github/list-organizations.ts, src/scripts/generate-targets-data.ts, test/scripts/generate-org-data.test.ts
Make using Github Enterprise Cloud more intuitive by falling back to github.com for Cloud enterprise if no custom url is provided instead of throwing an error
- https://github.com/snyk-tech-services/snyk-api-import/issues/314
=> feat: assume enterprise might include Github Enterprise Cloud

package.json, src/lib/api/org/index.ts, src/lib/types.ts, src/scripts/generate-imported-targets-from-snyk.ts, test/lib/org.test.ts
Using the API v3 instead of v1 to get the project list.
Tested manually as well as local regression.
=> feat: use api v3 get all projects endpoint

.circleci/config.yml
Drop the `snyk/scan` orb in favour of commit status checks
=> fix: drop snyk/scan in favour of commit status checks

docs/import.md
Clarify that user must use a personal API token for Github & service account for Github Enterprise
https://github.com/snyk-tech-services/snyk-api-import/issues/346
=> docs: clarify service account vs personal API token

src/lib/api/project/index.ts, test/lib/__snapshots__/projects.test.ts.snap, test/lib/projects.test.ts, test/system/projects.test.ts
Adding support for update the project branch using the v1 api.
The new function require a new env variable TEST_PROJECT_ID (already added to onepassword and circle)
Add e2e and unit tests
- [TECHSERV-3368](https://snyksec.atlassian.net/jira/software/c/projects/TECHSERV/boards/387?modal=detail&selectedIssue=TECHSERV-3368)
=> feat: add support for update project branch

src/lib/get-feature-flag-for-snyk-org.ts, test/lib/get-feature-flag.test.ts
Adds a function to fetch a FF from Snyk for a given org
- [Jira ticket](https://snyksec.atlassian.net/browse/TECHSERV-3388)
=> feat: add function to get feature flags from a snyk org

src/lib/api/feature-flags/index.ts, test/lib/api/feature-flags/index.test.ts
Move Snyk Api call code to `src/lib/api`
=> chore: move FF API calls to src/lib/api

test/lib/api/feature-flags/index.test.ts, test/lib/api/project/index.test.ts, test/lib/import-projects.test.ts, test/lib/org.test.ts, test/lib/orgs.test.ts, test/scripts/generate-org-data.test.ts, test/system/help.test.ts, test/system/import:data.test.ts, test/system/list:imported.test.ts, test/system/orgs:create.test.ts, test/system/orgs:data/bitbucket.test.ts, test/system/orgs:data/errors.test.ts, test/system/orgs:data/generic.test.ts, test/system/orgs:data/github.test.ts, test/system/orgs:data/gitlab.test.ts
Restore mocks back to original & drop unnecessary async
=> chore: reset mocks to original implementation

package.json, src/lib/api/feature-flags/index.ts, src/lib/api/org/index.ts, src/lib/project/compare-branches.ts, src/lib/types.ts, src/scripts/sync/sync-org-projects.ts, src/scripts/sync/sync-projects-per-target.ts, test/lib/api/feature-flags/index.test.ts, test/lib/org.test.ts, test/lib/project/compare-branches.test.ts, test/lib/project/update-project-per-target.test.ts, test/scripts/import-projects.test.ts, test/scripts/sync/sync-org-projects.test.ts
New function (for now not callable) that allows to `sync` all projects within a Snyk organization, specifically to update the default monitored branch in Snyk.
=> feat: sync organization targets for Github

docs/import-data.md, docs/mirror-bitbucket-cloud.md, docs/mirror-bitbucket-server.md, docs/mirror-github.md, docs/mirror-gitlab.md, src/cmds/import.ts, src/cmds/import:data.ts, src/cmds/list:imported.ts, src/scripts/generate-targets-data.ts, test/scripts/generate-targets-data.test.ts, test/system/import:data.test.ts, test/system/list:imported.test.ts
Remove the need for customers to provide a separate integration name in Snyk vs source name, which was to support a quirk that Github.com can be configured as Github Enterprise (but point to `github.com` in Snyk)
From now on assume both are the same, which they usually are. Users will need to provide `--source=github-enterprise` for that specific scenario where the project are Github.com but in Snyk we configured as Enterprise connection.
=> feat: assume integration type = source

src/cmds/sync.ts, src/scripts/sync/sync-org-projects.ts, src/scripts/sync/sync-projects-per-target.ts, test/scripts/sync/sync-org-projects.test.ts
- increase concurrent processing of targets to 50
- bail entirely with exit code 1 if a whole batch of targets fails straight away as something is likely wrong
=> fix: break early if a whole batch fails to sync

src/lib/index.ts, src/lib/supported-project-types/index.ts, src/lib/supported-project-types/supported-manifests.ts, test/lib/supported-project-types/index.test.ts
Library to get a list of supported manifest files per project type + project types for sync
Unused for now, nothing calling it
=> feat: supported manifest files per project type

src/lib/source-handlers/github/get-repo-metadata.ts, src/lib/source-handlers/github/index.ts, src/scripts/sync/sync-projects-per-target.ts, test/scripts/sync/sync-org-projects.test.ts
Return `cloneUrl` as well as branch info
=> refactor: get clone url info

src/lib/source-handlers/github/get-repo-metadata.ts, src/lib/source-handlers/github/list-repos.ts, src/lib/types.ts, test/scripts/sync/sync-org-projects.test.ts
Return sshUrl as part of repo meta so it can be used for cloning
=> refactor: return sshUrl as well

src/lib/api/project/index.ts, src/lib/supported-project-types/supported-manifests.ts, test/lib/supported-project-types/index.test.ts
Return supported manifest types by entitlements, by default OS project types only
=> fix: supported manifest types by entitlement

src/generate-target-id.ts, src/lib/api/import/index.ts
Don't send `id` unless it is Gitlab
=> fix: strip id from non Gitlab targets

src/scripts/sync/import-target.ts, test/scripts/sync/import-target.spec.ts
Function to import a single target with exclusions & files array. WIll be used shortly to import empty targets in `sync`
=> feat: function to import single target for sync

src/lib/api/import/index.ts, test/scripts/fixtures/import-projects-gitlab.json, test/scripts/import-projects.test.ts
Assuming Gitlab targets will always have 2 properties implies the tool & users created the exact correct target which is not a good assumption, dropping the check and at the same time reducing what ata is sent to the backend for Gitlab to only be `id` and `branch` in case backend validation gets stricter.
Adding an extra test for Gitlab import flow which will catch the issue next time.
=> fix: fix Gitlab target check

src/lib/source-handlers/gitlab/list-repos.ts, test/lib/source-handlers/gitlab/list-repos.test.ts
Exclude shared Gitlab projects but don;t exclude valid owned projects that are shared with other groups. Currently all projects that were shared were skipped which is a 🐛
=> Fix: exclude shared Gitlab projects but keep in the current group

test/system/orgs:create.test.ts, test/system/sync.test.ts
Read the test files a little after command stops
=> test: read log files after exit

src/lib/api/poll-import/index.ts, src/lib/types.ts, src/loggers/log-failed-projects.ts, src/scripts/sync/import-target.ts, src/scripts/sync/sync-projects-per-target.ts, test/scripts/sync/sync-org-projects.test.ts
Unused / not exposed yet functionality to bulk import files detected in a repo in batches > poll to completion > next batch. This will ensure support for large monorepos where thousands of files may need to be imported which can fail if they are all processed at once due to hitting rate limits.
=> feat: bulk import target file batches

src/scripts/sync/sync-projects-per-target.ts, test/scripts/sync/sync-org-projects.test.ts
Use targets data to create the target info needed to call Github APIs in case we have no projects in this target in Snyk yet
=> refactor: use target data not possibly empty projects data

docs/orgs.md, src/lib/source-handlers/gitlab/list-repos.ts, test/lib/source-handlers/gitlab/list-repos.test.ts, test/system/orgs:data/gitlab.test.ts
Some projects were being discarded due to several incorrect shared with group checks. Adding a test to ensure we can list projects from a sub-group & can see the group.
=> fix: include more Gitlab projects that are dropped by a bad shared check

src/scripts/sync/import-target.ts, src/scripts/sync/sync-projects-per-target.ts, test/scripts/sync/import-target.spec.ts, test/scripts/sync/sync-org-projects.test.ts
Refactor so the Integration ID can begrabbed once per org and not once per batch or target to reduce Snyk API calls
=> refactor: fetch integration id via API less

.circleci/config.yml, test/lib/index.test.ts
Update slack orb config to only post notifications on nightly jobs
=> chore: only post slack notifications on nightly test

docs/mirror-github.md
Mirror docs updated to share how sync can be used to avoid re-importing repos
=> chore: mirroring Github & GHE with sync command

src/scripts/sync/clone-and-analyze.ts
We've detected an incident where a customer's flow was broken due to a filesystem error when trying to delete a non-empty folder. Shouldn't really be possible as I see it, but it did happen.
This PR eases the logic to not break the flow and only render a warning in such cases.
=> fix: [SMA-145] Easing failure of rmdirSync

test/system/orgs:data/bitbucket.test.ts
Fixes a failing test for Bitbucket after a new repo was added to the test account.
=> test: Fix failing test for bitbucket orgs:data

test/scripts/generate-targets-data.test.ts, test/system/orgs:data/github.test.ts
Tweak test assertions since new token has less access
=> chore: update test assertions to match new token

test/system/orgs:data/generic.test.ts, test/system/orgs:data/github.test.ts
Remove last remaining GH_TOKEN references
=> chore: drop usage of gh_token

test/lib/source-handlers/gitlab/list-groups.test.ts, test/lib/source-handlers/gitlab/list-repos.test.ts, test/scripts/import-projects.test.ts
Small wait before reading log file that might take a bit longer to write
=> test: wait before reading log file

src/lib/api/poll-import/index.ts
Removes part of the changes from [this PR](https://github.com/snyk-tech-services/snyk-api-import/commit/64722b9b7a690591ea516414a4d77328f23f167b) as they are no longer needed and they introduce an infinite loop.
The 422s were happening when the job was persisted in import service but not in registry yet. We made a change that whenever that happens, registry queries import service and if the job exists there, we don't send 422 anymore. As a result, we don't need the retry anymore.
=> fix: remove infinite loop 422

.releaserc, package.json
Version 12.9.0 used previously had a bug that wouldn't delete folders recursively. This resulted in cloned repos not being deleted. Upgrading to the latest available v12 fixes the issue with the exception of alpine.
Nexe only supports alpine node 12.9.1 which does not have the fix yet. We will address that in a separate PR, for now unblocking other builds.
=> fix: bump node version to latest available 12

src/lib/source-handlers/bitbucket-server/list-repos.ts, test/system/fixtures/org-data/bitbucket-server-orgs.json
The BBS search endpoint matches by prefix, returning repos hosted in e.g. `bla-1` when searching for just project `bla`. In some cases this results in two Snyk projects created for the same manifest in different orgs.
This PR adds a condition to double-check that repos aren't being added to the wrong org.
This could also be fixed by switching to another API endpoint but prefer not to make this investment as the project is in maintenance mode now.
=> fix: match project keys exactly in BBS search

src/lib/source-handlers/bitbucket-server/list-repos.ts, src/lib/source-handlers/bitbucket-server/project-is-empty.ts, test/system/fixtures/org-data/bitbucket-server-orgs.json
Checks that the project name matches when listing repos for an org.
Renames variable from `projectKey` to `projectName` so that it's not confusing. The value is actually the name of the project in Bitbucket.
=> fix: check if project name matches when fetching repos

test/system/orgs:data/github.test.ts
The token now has access to 3 orgs rather than 2, updating the assertion to fix the pipeline.
=> chore: fix assertion after gh token changed

test/lib/source-handlers/gitlab/list-repos.test.ts, test/scripts/fixtures/import-projects-gitlab.json, test/scripts/generate-org-data.test.ts, test/scripts/import-projects.test.ts, test/system/fixtures/org-data/orgs.json, test/system/orgs:data/gitlab.test.ts
Migrate Gitlab contract tests to use gitlab.com instead of self-hosted Gitlab instance. This reduces the operational burden for teams at Snyk.
**Caution**:
Tests are randomly failing.
=> Feat: Migrate gitlab tests over to gitlab.com

test/system/fixtures/org-data/bitbucket-server-orgs.json, test/system/orgs:data/bitbucket.test.ts
Bitbucket  Server tests were failing because the BBS was moved to the backoffice instance. 
This PR fixes the failing BBS tests.
=> fix: fix Bitbucket Server tests

.circleci/config.yml
exclude test folder from open source scanning
=> chore: do not os security scan test files

package.json
Overrides vulnerable Axios version from `snyk-request-manager`.
Motivation for overriding `axios` instead of using later versions of the direct dependency is a breaking change introduced in `snyk-request-manager` 1.8.5 which enforces `api[.env].snyk.io` URLs, potentially causing customer configurations to stop working. Any existing users that supply `SNYK_API` env vars with the old `[env.][app.]snyk.io/api` format would start seeing errors and failures.
As the Axios vuln needs addressing ASAP and a complete API URL handling fix would take significant time, an override is called for.
=> fix: override vulnerable axios version

src/lib/source-handlers/azure/list-repos.ts, test/lib/fixtures/azure/org-repos.json, test/lib/source-handlers/azure/azure.test.ts, test/system/orgs:data/gitlab.test.ts
Ignores disabled Azure repos from listing as they cause 404 error when attempting to import.
- [#ask-import request](https://snyk.slack.com/archives/C06RJJY6Y4A/p1730318407230459)
=> fix: ignore disabled azure repos from listing

test/scripts/import-projects.test.ts
The tests are currently [failing the pipeline](https://app.circleci.com/pipelines/github/snyk/snyk-api-import), and it looks like individual tests are affecting each other - when running each failing test in isolation, they pass. Although it's not clear how they affect each other, a longer cool off period between the import-projects tests allows them enough time to do whatever cleanup needs to happen remotely, thus [fixing the tests](https://app.circleci.com/pipelines/github/snyk/snyk-api-import/3824/workflows/9162bca6-ddcd-43f1-b612-7da861c3bc99/jobs/4039).
Hide whitespaces when reviewing, as the diff is actually a lot smaller.
=> fix: allow cool off between import-projects tests for cleanup
